-- 种子数据：博主 + 两类分类 + 真实视频（170 条）+ 标签（14 条）+ 关联（251 条）+ 文章（6 条）
-- media_key 即对象 key：作者视频用 <作者slug>/<视频slug>.mp4（mark-tech-workshop/ 前缀），其余为 bucket 根目录平铺。
-- 封面走 OSS covers/ 前缀（anonymous download）；视频走 OSS 私有+预签名。
-- 文章为补充内容种子。

INSERT INTO blogger (id, name, avatar, introduction) VALUES
  (1, '李某某的AI课', 'https://placehold.co/200?text=AI%E8%AF%BE', '专注大模型工程化落地，热衷分享 RAG 实战'),
  (2, 'Harness实验室', 'https://placehold.co/200?text=Harness', '深入解析 Agent 与工具编排、Harness 框架'),
  (3, 'MCP研究所', 'https://placehold.co/200?text=MCP', '研究 Model Context Protocol 协议与生态'),
  (4, 'LLM入门指南', 'https://placehold.co/200?text=LLM', '零基础到大模型应用开发的学习路线'),
  (5, '马克的技术工作坊', 'https://placehold.co/200?text=mark-tech-workshop', '专注 AI 工程化与智能体实践，覆盖 MCP、Agent、RAG、AI 编程等前沿技术'),
  (7, '木子不写代码', 'https://placehold.co/200?text=muzi-buxie-daima', '专注 AI 编程与智能体实战，覆盖 Claude Code、OpenClaw、n8n、RAG 等前沿工具'),
  (8, 'autoGPT', 'https://placehold.co/200?text=autogpt', 'AutoGPT 官方平台教程与 Agent 实战，覆盖 AutoPilot、Agent Blocks、论文解读'),
  (9, '3Blue1Brown', 'https://placehold.co/200?text=3blue1brown', '数学与深度学习的直觉可视化教学，覆盖神经网络、Transformer、线性代数等原理');

INSERT INTO category (id, name, cat_key, cat_type) VALUES
  (1, '智能体框架', 'harness', 'video_tech'),
  (2, 'MCP协议', 'mcp', 'video_tech'),
  (3, 'RAG检索', 'rag', 'video_tech'),
  (4, '提示词工程', 'prompt', 'video_tech'),
  (9, 'AI编程', 'ai-coding', 'video_tech'),
  (10, 'AI动态', 'ai-trends', 'video_tech'),
  (11, '基础概念', 'fundamentals', 'video_tech'),
  (5, '李某某的AI课', 'blogger_1', 'blogger'),
  (6, 'Harness实验室', 'blogger_2', 'blogger'),
  (7, 'MCP研究所', 'blogger_3', 'blogger'),
  (8, 'LLM入门指南', 'blogger_4', 'blogger'),
  (12, '马克的技术工作坊', 'blogger_5', 'blogger'),
  (13, '木子不写代码', 'blogger_7', 'blogger'),
  (14, 'autoGPT', 'blogger_8', 'blogger'),
  (15, '3Blue1Brown', 'blogger_9', 'blogger');

-- 封面：bucket covers/ 前缀（anonymous download，免登录展示）；地址用网关绝对路径。
INSERT INTO video (id, title, blogger_id, category_id, cover, media_key, duration, hot_score, source_type, play_url) VALUES
  (1, 'AI最前沿的人，已经不聊模型了#aicoding #易论AI #归藏 #colaOS #李继刚', NULL, 10,
   'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/ai-frontier.jpg', 'ai-frontier.mp4', 0, 0, 'minio', NULL),
  (2, 'Harness Engineering 到底是什么？概念、实战与争议，一次全部讲清楚', 5, 1,
   'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/harness-engineering-explained.jpg', 'harness-engineering-explained.mp4', 0, 0, 'minio', NULL),
  (3, 'RAG 工作机制详解——一个高质量知识库背后的技术全流程', 5, 3,
   'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/rag-workflow-deep-dive.jpg', 'rag-workflow-deep-dive.mp4', 0, 0, 'minio', NULL),
  (4, 'Token 到底是什么？—— 揭秘大模型背后的“文字压缩术”', 5, 11,
   'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/what-is-token.jpg', 'what-is-token.mp4', 0, 0, 'minio', NULL),
  (5, '如何使用第三方模型驱动 Codex（无需 OpenAI 账号）', 5, 9,
   'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/drive-codex-thirdparty-models.jpg', 'drive-codex-thirdparty-models.mp4', 0, 0, 'minio', NULL),
  (6, '我的 AI 编程全流程：如何使用 AI 稳定交付一个高质量的产品', 5, 9,
   'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/my-ai-coding-workflow.jpg', 'my-ai-coding-workflow.mp4', 0, 0, 'minio', NULL),
  (7, '5分钟教会你如何本地部署DeepSeek-R1，无需联网，全程干货，没有一句废话', 5, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/mark-tech-workshop/deploy-deepseek-r1-locally.jpg', 'mark-tech-workshop/deploy-deepseek-r1-locally.mp4', 346, 0, 'oss', NULL),
  (8, '5种使用Deepseek打造可视化内容的方法，构建创意视觉图和专业数据分析报表，增强画面冲击力，可直接用在PPT，总结报告和视频解说中，总有一款适合你！', 5, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/mark-tech-workshop/deepseek-visual-content-ideas.jpg', 'mark-tech-workshop/deepseek-visual-content-ideas.mp4', 449, 0, 'oss', NULL),
  (9, '6分钟快速上手最强学习工具NotebookLM（2025）', 5, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/mark-tech-workshop/notebooklm-quick-start.jpg', 'mark-tech-workshop/notebooklm-quick-start.mp4', 362, 0, 'oss', NULL),
  (10, 'A2A协议深度解析（第 1 部分：双Agent同步调用场景）', 5, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/mark-tech-workshop/a2a-protocol-part1.jpg', 'mark-tech-workshop/a2a-protocol-part1.mp4', 2144, 0, 'oss', NULL),
  (11, 'A2A协议深度解析（第 2 部分：流式返回 + 多 Agent 场景）', 5, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/mark-tech-workshop/a2a-protocol-part2.jpg', 'mark-tech-workshop/a2a-protocol-part2.mp4', 1037, 0, 'oss', NULL),
  (12, 'Agent Skill 从使用到原理，一次讲清', 5, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/mark-tech-workshop/agent-skill-explained.jpg', 'mark-tech-workshop/agent-skill-explained.mp4', 1061, 0, 'oss', NULL),
  (13, 'Agent 的概念、原理与构建模式 —— 从零打造一个简化版的 Claude Code', 5, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/mark-tech-workshop/agent-concepts-and-patterns.jpg', 'mark-tech-workshop/agent-concepts-and-patterns.mp4', 1686, 0, 'oss', NULL),
  (14, 'Claude Code 从 0 到 1 全攻略 —— MCP ⧸ SubAgent ⧸ Agent Skill ⧸ Hook ⧸ 图片 ⧸ 上下文处理⧸ 后台任务 ⧸ 权限', 5, 9, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/mark-tech-workshop/claude-code-complete-guide.jpg', 'mark-tech-workshop/claude-code-complete-guide.mp4', 2684, 0, 'oss', NULL),
  (15, 'Codex 从 0 到 1 全攻略 - Annotate ⧸ Fork ⧸ Archive ⧸ Plan ⧸ Plugin ⧸ Skill ⧸ Automation ⧸ Mobile', 5, 9, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/mark-tech-workshop/codex-complete-guide.jpg', 'mark-tech-workshop/codex-complete-guide.mp4', 3517, 0, 'oss', NULL),
  (16, 'Context Engineering：概念与技术实现深度解析', 5, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/mark-tech-workshop/context-engineering-deep-dive.jpg', 'mark-tech-workshop/context-engineering-deep-dive.mp4', 915, 0, 'oss', NULL),
  (17, 'DeepSeek R1 真的那么强吗？客观评测 R1 与 o1 在编程、推理方面的效果', 5, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/mark-tech-workshop/deepseek-r1-vs-o1-review.jpg', 'mark-tech-workshop/deepseek-r1-vs-o1-review.mp4', 1348, 0, 'oss', NULL),
  (18, 'GPT 4o 图片生成能力评测', 5, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/mark-tech-workshop/gpt4o-image-generation-review.jpg', 'mark-tech-workshop/gpt4o-image-generation-review.mp4', 690, 0, 'oss', NULL),
  (19, 'Keynote 动画制作全流程，以及我对 AI 动画的一些看法', 5, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/mark-tech-workshop/keynote-animation-workflow.jpg', 'mark-tech-workshop/keynote-animation-workflow.mp4', 3172, 0, 'oss', NULL),
  (20, 'MCP 与 Function Calling 到底什么关系 —— 以及为什么我认为大部分人的观点都是错误的', 5, 2, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/mark-tech-workshop/mcp-vs-function-calling.jpg', 'mark-tech-workshop/mcp-vs-function-calling.mp4', 1636, 0, 'oss', NULL),
  (21, 'MCP终极指南   带你深入掌握MCP（进阶篇）', 5, 2, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/mark-tech-workshop/mcp-guide-advanced.jpg', 'mark-tech-workshop/mcp-guide-advanced.mp4', 1640, 0, 'oss', NULL),
  (22, 'MCP终极指南 - 从原理到实战，带你深入掌握MCP（基础篇）', 5, 2, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/mark-tech-workshop/mcp-guide-basics.jpg', 'mark-tech-workshop/mcp-guide-basics.mp4', 1625, 0, 'oss', NULL),
  (23, 'MCP终极指南 - 番外篇：抓包分析 Cline 与模型的交互协议（内含 Agent 的实现原理）', 5, 2, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/mark-tech-workshop/mcp-guide-extra-capture.jpg', 'mark-tech-workshop/mcp-guide-extra-capture.mp4', 2644, 0, 'oss', NULL),
  (24, 'Manus案例深度解析 - 以及我对它的看法', 5, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/mark-tech-workshop/manus-case-analysis.jpg', 'mark-tech-workshop/manus-case-analysis.mp4', 460, 0, 'oss', NULL),
  (25, 'Midjourney 2025 网页版完整教学 - 从基础到进阶', 5, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/mark-tech-workshop/midjourney-2025-web-tutorial.jpg', 'mark-tech-workshop/midjourney-2025-web-tutorial.mp4', 1262, 0, 'oss', NULL),
  (26, 'OpenAI 的 RAG 范例，无需向量化', 5, 3, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/mark-tech-workshop/openai-rag-example.jpg', 'mark-tech-workshop/openai-rag-example.mp4', 1163, 0, 'oss', NULL),
  (27, 'Temperature & Top-p：掌控大模型的创造力开关', 5, 4, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/mark-tech-workshop/temperature-top-p.jpg', 'mark-tech-workshop/temperature-top-p.mp4', 1047, 0, 'oss', NULL),
  (28, 'o3-mini-high编程与推理能力评测', 5, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/mark-tech-workshop/o3-mini-high-review.jpg', 'mark-tech-workshop/o3-mini-high-review.mp4', 1062, 0, 'oss', NULL),
  (29, 'o3、o4 mini high数学和推理能力评测', 5, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/mark-tech-workshop/o3-o4-mini-high-math-review.jpg', 'mark-tech-workshop/o3-o4-mini-high-math-review.mp4', 1518, 0, 'oss', NULL),
  (30, '为什么越来越多的人抛弃 MCP，转向 CLI？', 5, 2, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/mark-tech-workshop/why-cli-over-mcp.jpg', 'mark-tech-workshop/why-cli-over-mcp.mp4', 938, 0, 'oss', NULL),
  (31, '从 LLM 到 Agent Skill，一期视频带你打通底层逻辑！', 5, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/mark-tech-workshop/llm-to-agent-skill.jpg', 'mark-tech-workshop/llm-to-agent-skill.mp4', 1951, 0, 'oss', NULL),
  (32, '使用 Cursor 和 Claude3 7 10分钟构建产品原型图和iOS应用，无需写一行代码', 5, 9, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/mark-tech-workshop/cursor-claude-prototype.jpg', 'mark-tech-workshop/cursor-claude-prototype.mp4', 439, 0, 'oss', NULL),
  (33, '使用 DeepSeek R1 与 AnythingLLM 搭建本地知识库', 5, 3, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/mark-tech-workshop/deepseek-anythingllm-rag.jpg', 'mark-tech-workshop/deepseek-anythingllm-rag.mp4', 620, 0, 'oss', NULL),
  (34, '使用Python构建RAG系统 —— 用代码还原 RAG系统的每个细节', 5, 3, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/mark-tech-workshop/python-rag-from-scratch.jpg', 'mark-tech-workshop/python-rag-from-scratch.mp4', 1050, 0, 'oss', NULL),
  (35, '四大推理大模型数学与编程能力评测   Grok3、Claude3 7、DeepSeep R1、o3 mini high 到底谁的推理能力最强？', 5, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/mark-tech-workshop/top4-reasoning-models-review.jpg', 'mark-tech-workshop/top4-reasoning-models-review.mp4', 1502, 0, 'oss', NULL),
  (36, '把 Gemini Flash 2 0 当 PS 使用的正确方法', 5, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/mark-tech-workshop/gemini-flash-as-photoshop.jpg', 'mark-tech-workshop/gemini-flash-as-photoshop.mp4', 501, 0, 'oss', NULL),
  (37, '0基础做AI应用：从想法到上线的终极教程', 7, 9, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/001.jpg', 'muzi-buxie-daima/001.mp4', 2787, 0, 'oss', NULL),
  (38, '2025如何找到最佳的创业赛道？｜ 5个发掘百万市场需求的秘密方法 ！ 一个视频解决软件创业选题难题', 7, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/002.jpg', 'muzi-buxie-daima/002.mp4', 578, 0, 'oss', NULL),
  (39, '2025年度AI进展大总结！', 7, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/003.jpg', 'muzi-buxie-daima/003.mp4', 685, 0, 'oss', NULL),
  (40, '6分钟了解GPT5的真实性能：对比Claude Opus 4.1和Gemini 2.5 Pro', 7, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/004.jpg', 'muzi-buxie-daima/004.mp4', 414, 0, 'oss', NULL),
  (41, '7分钟学会搭建AI应用！', 7, 9, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/005.jpg', 'muzi-buxie-daima/005.mp4', 445, 0, 'oss', NULL),
  (42, 'AI做PPT零基础终极教程！', 7, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/006.jpg', 'muzi-buxie-daima/006.mp4', 1632, 0, 'oss', NULL),
  (43, 'AI复刻爆款短视频全流程！开源免费＋批量生成！', 7, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/007.jpg', 'muzi-buxie-daima/007.mp4', 308, 0, 'oss', NULL),
  (44, 'AI文案太假？我开源了会自己进化文案的Skill！', 7, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/008.jpg', 'muzi-buxie-daima/008.mp4', 514, 0, 'oss', NULL),
  (45, 'AI生图新王Nano Banana PRO！6大场景实测对比GPT和Grok生图！', 7, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/009.jpg', 'muzi-buxie-daima/009.mp4', 468, 0, 'oss', NULL),
  (46, 'Claude Code 零基础终极教程：安装、换模型、插件、Hooks、Skills、Subagents、实战项目一次讲透！', 7, 9, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/010.jpg', 'muzi-buxie-daima/010.mp4', 3179, 0, 'oss', NULL),
  (47, 'Claude Code天价源码泄露！小白也能看懂的源码拆解+核心策略！', 7, 9, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/011.jpg', 'muzi-buxie-daima/011.mp4', 714, 0, 'oss', NULL),
  (48, 'Codex 零基础终极教程：功能、办公、编程、自动化一次讲透！', 7, 9, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/012.jpg', 'muzi-buxie-daima/012.mp4', 1324, 0, 'oss', NULL),
  (49, 'GPT5.5 vs Claude Opus 4.7：实测谁才是最强模型！', 7, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/013.jpg', 'muzi-buxie-daima/013.mp4', 638, 0, 'oss', NULL),
  (50, 'Github 零基础终极教程！', 7, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/014.jpg', 'muzi-buxie-daima/014.mp4', 2250, 0, 'oss', NULL),
  (51, 'OpenClaw + Minimax M2.7，10分钟做出1000美元高端动效网站！', 7, 9, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/015.jpg', 'muzi-buxie-daima/015.mp4', 459, 0, 'oss', NULL),
  (52, 'OpenClaw 这 3 个小功能，能让你少走 80% 的弯路', 7, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/016.jpg', 'muzi-buxie-daima/016.mp4', 519, 0, 'oss', NULL),
  (53, '【AI教程】 手把手教你打造AI实时语音客服⧸私人助理 ｜ 零代码 ｜ n8n⧸ElevenLabs', 7, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/017.jpg', 'muzi-buxie-daima/017.mp4', 906, 0, 'oss', NULL),
  (54, '【AI教程】6个案例带你真正搞懂AI工作流⧸AI Agent 突破大语言模型的能力上限', 7, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/018.jpg', 'muzi-buxie-daima/018.mp4', 1074, 0, 'oss', NULL),
  (55, '【AI教程】如何让DeepSeek和GPT 24H＊7为你打工｜构建全自动AI博主｜零基础AI Agent教学', 7, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/019.jpg', 'muzi-buxie-daima/019.mp4', 1407, 0, 'oss', NULL),
  (56, '【AI教程】零基础入门RAG ｜ 手把手教你打造AI智能客服⧸知识库（n8n⧸coze双平台实战）', 7, 3, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/020.jpg', 'muzi-buxie-daima/020.mp4', 1957, 0, 'oss', NULL),
  (57, '【AI教程】零基础学会AI全自动短视频生成｜打造自媒体被动收入系统', 7, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/021.jpg', 'muzi-buxie-daima/021.mp4', 1304, 0, 'oss', NULL),
  (58, '【AI编程】超10倍性价比的DeepSeek+Cline完胜Cursor？ 效果意想不到的好！如何设置+快速对比', 7, 9, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/022.jpg', 'muzi-buxie-daima/022.mp4', 480, 0, 'oss', NULL),
  (59, '【Deepseek要干掉初级数据分析师啦｜n8n】手把手教在n8n里, 做一个根据SQL返还表格结果画图的AI工作流，并打包成从查数据到画图完全纯自然语言，零代码的一站式聊天工具。', 7, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/023.jpg', 'muzi-buxie-daima/023.mp4', 621, 0, 'oss', NULL),
  (60, '【Deepseek零代码查数据库】如何在n8n中搭建工作流，自然语言零SQL代码用AI agent查询数据库', 7, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/024.jpg', 'muzi-buxie-daima/024.mp4', 806, 0, 'oss', NULL),
  (61, '【保姆教程】3分钟学会用AI编程 ｜ 掌握Cursor无代码程序开发', 7, 9, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/025.jpg', 'muzi-buxie-daima/025.mp4', 230, 0, 'oss', NULL),
  (62, '【保姆教程】4分钟学会用AI制作Chrome插件 ｜ 轻松掌握零代码CursorAI编程开发谷歌浏览器插件', 7, 9, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/026.jpg', 'muzi-buxie-daima/026.mp4', 253, 0, 'oss', NULL),
  (63, '【保姆教程】4种方法将 OpenClaw 成本降低10倍 ｜直降95%+ Token 消耗！', 7, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/027.jpg', 'muzi-buxie-daima/027.mp4', 505, 0, 'oss', NULL),
  (64, '【零基础保姆教程】OpenClaw浏览器自动化：从API抓取到 24⧸7 完全接管', 7, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/028.jpg', 'muzi-buxie-daima/028.mp4', 927, 0, 'oss', NULL),
  (65, '【零基础保姆教程】上手最强AI智能体OpenClaw ｜设备选择｜模型选择｜openclaw部署｜telegram连接', 7, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/029.jpg', 'muzi-buxie-daima/029.mp4', 636, 0, 'oss', NULL),
  (66, '【零基础保姆教程】让AI也有记忆窗口！｜ 原理+实现 ｜ 上下文工程教程02', 7, 4, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/030.jpg', 'muzi-buxie-daima/030.mp4', 1388, 0, 'oss', NULL),
  (67, '不用 GPT 账号！国产模型接入 Codex 保姆级教程', 7, 9, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/031.jpg', 'muzi-buxie-daima/031.mp4', 338, 0, 'oss', NULL),
  (68, '从0做出你的第一个App ｜ 零基础AI编程保姆教程', 7, 9, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/032.jpg', 'muzi-buxie-daima/032.mp4', 1512, 0, 'oss', NULL),
  (69, '从0到1：Codex全自动做商业大片！', 7, 9, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/033.jpg', 'muzi-buxie-daima/033.mp4', 266, 0, 'oss', NULL),
  (70, '史上最强AI设计师！Anthropic 新产品 Claude Design 实战教学！', 7, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/034.jpg', 'muzi-buxie-daima/034.mp4', 544, 0, 'oss', NULL),
  (71, '实测GPT Image 2 vs Nano Banana2：谁才是最强AI生图模型？', 7, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/035.jpg', 'muzi-buxie-daima/035.mp4', 603, 0, 'oss', NULL),
  (72, '实测豆包工作真实能力！3大办公场景实战', 7, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/036.jpg', 'muzi-buxie-daima/036.mp4', 381, 0, 'oss', NULL),
  (73, '实测！DeepseekV4 vs GPT5.5 vs Opus4.7！', 7, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/037.jpg', 'muzi-buxie-daima/037.mp4', 833, 0, 'oss', NULL),
  (74, '实测！Hermes Agent真的比OpenClaw更好吗？实战⧸原理⧸如何安装详解', 7, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/038.jpg', 'muzi-buxie-daima/038.mp4', 678, 0, 'oss', NULL),
  (75, '小白到高手！零基础OpenClaw系统教程：安装、实操、降本、AI团队搭建！', 7, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/039.jpg', 'muzi-buxie-daima/039.mp4', 3178, 0, 'oss', NULL),
  (76, '开源！这个系统，能把OpenClaw聊天直接养成 Skills！', 7, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/040.jpg', 'muzi-buxie-daima/040.mp4', 346, 0, 'oss', NULL),
  (77, '快速用AI看懂SpaceX值不值2.4万亿', 7, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/041.jpg', 'muzi-buxie-daima/041.mp4', 398, 0, 'oss', NULL),
  (78, '想被AI推荐？你必须知道这些！GEO｜ 大模型搜索优化', 7, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/042.jpg', 'muzi-buxie-daima/042.mp4', 1260, 0, 'oss', NULL),
  (79, '我实现了OpenClaw 多智能体群聊、自动任务交接！', 7, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/043.jpg', 'muzi-buxie-daima/043.mp4', 459, 0, 'oss', NULL),
  (80, '我用 OpenClaw 搭了一支 AI 团队｜这可能是 AI 时代最强的个人外挂', 7, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/044.jpg', 'muzi-buxie-daima/044.mp4', 850, 0, 'oss', NULL),
  (81, '我用20分钟组建了一个AI智能体团队，干掉了90%的日常工作 [保姆教程]', 7, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/045.jpg', 'muzi-buxie-daima/045.mp4', 1304, 0, 'oss', NULL),
  (82, '手机能跑+强到离谱？！Google 开源 Gemma 4，真得这么好吗？', 7, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/046.jpg', 'muzi-buxie-daima/046.mp4', 581, 0, 'oss', NULL),
  (83, '效率X10！我开源了一个OpenClaw的控制中心', 7, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/047.jpg', 'muzi-buxie-daima/047.mp4', 303, 0, 'oss', NULL),
  (84, '断档领先！Anthropic官宣新模型Mythos！', 7, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/048.jpg', 'muzi-buxie-daima/048.mp4', 281, 0, 'oss', NULL),
  (85, '最强AI工作流工具n8n终极入门教学｜从业余小白到职业高手', 7, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/049.jpg', 'muzi-buxie-daima/049.mp4', 4500, 0, 'oss', NULL),
  (86, '未来希望！ 新模型DeepSeek-OCR解析：上下文革命', 7, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/050.jpg', 'muzi-buxie-daima/050.mp4', 405, 0, 'oss', NULL),
  (87, '永别了n8n!  Anthropic发布新产品Claude Managed Agents！', 7, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/051.jpg', 'muzi-buxie-daima/051.mp4', 509, 0, 'oss', NULL),
  (88, '爆肝3亿token！我把 10 种高级数据动画，做成了开箱即用', 7, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/052.jpg', 'muzi-buxie-daima/052.mp4', 508, 0, 'oss', NULL),
  (89, '能进公司当同事的AI，真的来了！3大场景实测！', 7, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/053.jpg', 'muzi-buxie-daima/053.mp4', 446, 0, 'oss', NULL),
  (90, '让大模型的输出效果好5倍 ！- 上下文工程教程01之简单提示词', 7, 4, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/054.jpg', 'muzi-buxie-daima/054.mp4', 448, 0, 'oss', NULL),
  (91, '这个视频开头，100%都是AI做的', 7, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/055.jpg', 'muzi-buxie-daima/055.mp4', 365, 0, 'oss', NULL),
  (92, '零基础AI生图终极教程！', 7, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/056.jpg', 'muzi-buxie-daima/056.mp4', 1275, 0, 'oss', NULL),
  (93, '零基础入门AI自动化 ｜ n8n大师课  (理论介绍+功能拆解+案例讲解)', 7, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/057.jpg', 'muzi-buxie-daima/057.mp4', 1506, 0, 'oss', NULL),
  (94, '零基礎建構能自動幫忙找工作的 AI 智能體｜n8n AI Agent', 7, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/058.jpg', 'muzi-buxie-daima/058.mp4', 1135, 0, 'oss', NULL),
  (95, '零基礎構建能自我學習的AI智能體 ｜ 牢記你所有說過的文字語音和圖片｜ n8n AI Agent', 7, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/059.jpg', 'muzi-buxie-daima/059.mp4', 2300, 0, 'oss', NULL),
  (96, '零门槛上手OpenClaw：10 个最实用Skills技能包！', 7, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/muzi-buxie-daima/060.jpg', 'muzi-buxie-daima/060.mp4', 542, 0, 'oss', NULL),
  (97, '10 Candidates Sourced and Ranked — AutoPilot Demo', 8, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/001.jpg', 'autogpt/001.mp4', 92, 0, 'oss', NULL),
  (98, 'Agent Blocks Demo： Automate Prospecting into Personalized Outreach at Scale', 8, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/002.jpg', 'autogpt/002.mp4', 197, 0, 'oss', NULL),
  (99, 'April 16, 2023 Auto-GPT Demo', 8, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/003.jpg', 'autogpt/003.mp4', 62, 0, 'oss', NULL),
  (100, 'AutoGPT Maintainer Meeting Live Stream Aug 8th', 8, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/004.jpg', 'autogpt/004.mp4', 2440, 0, 'oss', NULL),
  (101, 'AutoGPT v0.4.0 Release Updates', 8, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/005.jpg', 'autogpt/005.mp4', 263, 0, 'oss', NULL),
  (102, 'AutoGPT： How to Contribute', 8, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/006.jpg', 'autogpt/006.mp4', 205, 0, 'oss', NULL),
  (103, 'AutoPilot Demo — Five Real Tasks, One Prompt Each ｜ AutoGPT Platform', 8, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/007.jpg', 'autogpt/007.mp4', 390, 0, 'oss', NULL),
  (104, 'Automated Weekly Bug Triage — AutoPilot Demo', 8, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/008.jpg', 'autogpt/008.mp4', 86, 0, 'oss', NULL),
  (105, 'Build Your Own AI Answer Engine with AutoGPT & Claude 3.5 Sonnet (Intermediate Example)', 8, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/009.jpg', 'autogpt/009.mp4', 1056, 0, 'oss', NULL),
  (106, 'Build an AI Agent with AutoGPT', 8, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/010.jpg', 'autogpt/010.mp4', 90, 0, 'oss', NULL),
  (107, 'Create a Basic AI Agent with AutoGPT： Calculator Agent Example', 8, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/011.jpg', 'autogpt/011.mp4', 141, 0, 'oss', NULL),
  (108, 'Create a Basic AI Agent with AutoGPT： Q&A Agent Example', 8, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/012.jpg', 'autogpt/012.mp4', 111, 0, 'oss', NULL),
  (109, 'Create an AI Agent as a Block in AutoGPT', 8, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/013.jpg', 'autogpt/013.mp4', 176, 0, 'oss', NULL),
  (110, 'Delete an AI Agent in AutoGPT', 8, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/014.jpg', 'autogpt/014.mp4', 29, 0, 'oss', NULL),
  (111, 'Download & Import an Agent for Local Host Users in AutoGPT', 8, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/015.jpg', 'autogpt/015.mp4', 77, 0, 'oss', NULL),
  (112, 'Edit an AI Agent in AutoGPT', 8, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/016.jpg', 'autogpt/016.mp4', 31, 0, 'oss', NULL),
  (113, 'Full Competitive Analysis — AutoPilot Demo', 8, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/017.jpg', 'autogpt/017.mp4', 83, 0, 'oss', NULL),
  (114, 'Full Sales Pipeline — AutoPilot Demo', 8, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/018.jpg', 'autogpt/018.mp4', 72, 0, 'oss', NULL),
  (115, 'Gorilla Large Language Model Connected with Massive APIs', 8, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/019.jpg', 'autogpt/019.mp4', 3200, 0, 'oss', NULL),
  (116, 'How to Export an Agent in AutoGPT', 8, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/020.jpg', 'autogpt/020.mp4', 44, 0, 'oss', NULL),
  (117, 'How to Login to the AutoGPT Platform', 8, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/021.jpg', 'autogpt/021.mp4', 19, 0, 'oss', NULL),
  (118, 'How to Set Up AutoGPT： Self-Hosted Tutorial', 8, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/022.jpg', 'autogpt/022.mp4', 166, 0, 'oss', NULL),
  (119, 'Introducing the AutoGPT Platform', 8, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/023.jpg', 'autogpt/023.mp4', 66, 0, 'oss', NULL),
  (120, 'LLM Blender Ensembling Large Language Models with Pairwise Ranking and Generative Fusion', 8, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/024.jpg', 'autogpt/024.mp4', 1758, 0, 'oss', NULL),
  (121, 'LLM+P Empowering Large Language Models with Optimal Planning Proficiency', 8, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/025.jpg', 'autogpt/025.mp4', 2538, 0, 'oss', NULL),
  (122, 'MEGABYTE Predicting Million byte Sequences with Multiscale Transformers', 8, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/026.jpg', 'autogpt/026.mp4', 4364, 0, 'oss', NULL),
  (123, 'ReWOO Decoupling Reasoning from Observations for Efficient Augmented Language Models', 8, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/027.jpg', 'autogpt/027.mp4', 2360, 0, 'oss', NULL),
  (124, 'Release Notes to Customer Email — AutoPilot Demo', 8, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/028.jpg', 'autogpt/028.mp4', 65, 0, 'oss', NULL),
  (125, 'SPRING GPT 4 Out performs RL Algorithms by Studying Papers and Reasoning', 8, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/029.jpg', 'autogpt/029.mp4', 2662, 0, 'oss', NULL),
  (126, 'Submit an AI Agent to the AutoGPT Marketplace', 8, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/030.jpg', 'autogpt/030.mp4', 82, 0, 'oss', NULL),
  (127, 'The Agent Era： How AI Agents Went From Toy to Team (2023–2026)', 8, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/031.jpg', 'autogpt/031.mp4', 168, 0, 'oss', NULL),
  (128, 'Tree of Thoughts Deliberate Problem Solving with Large Language Models', 8, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/032.jpg', 'autogpt/032.mp4', 4299, 0, 'oss', NULL),
  (129, 'Voyager An Open Ended Embodied Agent with Large Language Models', 8, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/033.jpg', 'autogpt/033.mp4', 3606, 0, 'oss', NULL),
  (130, 'Welcome To The AutoGPT Hacks Arena!', 8, 1, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/034.jpg', 'autogpt/034.mp4', 727, 0, 'oss', NULL),
  (131, 'WizardLM： Empowering Large Language Models to Follow Complex Instructions', 8, 10, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/autogpt/035.jpg', 'autogpt/035.mp4', 2252, 0, 'oss', NULL),
  (132, 'A pretty reason why Gaussian + Gaussian = Gaussian', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/001.jpg', '3blue1brown/001.mp4', 795, 0, 'oss', NULL),
  (133, 'A simple image convolution', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/002.jpg', '3blue1brown/002.mp4', 58, 0, 'oss', NULL),
  (134, 'Attention in transformers, step-by-step ｜ Deep Learning Chapter 6', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/003.jpg', '3blue1brown/003.mp4', 1569, 0, 'oss', NULL),
  (135, 'Backpropagation calculus ｜ Deep Learning Chapter 4', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/004.jpg', '3blue1brown/004.mp4', 617, 0, 'oss', NULL),
  (136, 'Backpropagation, intuitively ｜ Deep Learning Chapter 3', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/005.jpg', '3blue1brown/005.mp4', 766, 0, 'oss', NULL),
  (137, 'Bayes theorem, the geometry of changing beliefs', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/006.jpg', '3blue1brown/006.mp4', 910, 0, 'oss', NULL),
  (138, 'But how do AI images and videos actually work？ ｜ Guest video by Welch Labs', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/007.jpg', '3blue1brown/007.mp4', 2239, 0, 'oss', NULL),
  (139, 'But what is a Fourier series？  From heat flow to drawing with circles ｜ DE4', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/008.jpg', '3blue1brown/008.mp4', 1486, 0, 'oss', NULL),
  (140, 'But what is a Laplace Transform？', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/009.jpg', '3blue1brown/009.mp4', 2080, 0, 'oss', NULL),
  (141, 'But what is a convolution？', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/010.jpg', '3blue1brown/010.mp4', 1380, 0, 'oss', NULL),
  (142, 'But what is a neural network？ ｜ Deep learning chapter 1', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/011.jpg', '3blue1brown/011.mp4', 1119, 0, 'oss', NULL),
  (143, 'But what is cross-entropy？ ｜ Compression is Intelligence Part 2', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/012.jpg', '3blue1brown/012.mp4', 2030, 0, 'oss', NULL),
  (144, 'But what is quantum computing？  (Grover''s Algorithm)', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/013.jpg', '3blue1brown/013.mp4', 2213, 0, 'oss', NULL),
  (145, 'But what is the Fourier Transform？  A visual introduction', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/014.jpg', '3blue1brown/014.mp4', 1181, 0, 'oss', NULL),
  (146, 'Change of basis ｜ Chapter 13, Essence of linear algebra', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/015.jpg', '3blue1brown/015.mp4', 770, 0, 'oss', NULL),
  (147, 'Convolutions ｜ Why X+Y in probability is a beautiful mess', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/016.jpg', '3blue1brown/016.mp4', 1644, 0, 'oss', NULL),
  (148, 'Divergence and curl：  The language of Maxwell''s equations, fluid flow, and more', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/017.jpg', '3blue1brown/017.mp4', 941, 0, 'oss', NULL),
  (149, 'Dot products and duality ｜ Chapter 9, Essence of linear algebra', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/018.jpg', '3blue1brown/018.mp4', 851, 0, 'oss', NULL),
  (150, 'Gradient descent, how neural networks learn ｜ Deep Learning Chapter 2', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/019.jpg', '3blue1brown/019.mp4', 1233, 0, 'oss', NULL),
  (151, 'Hilbert''s Curve： Is infinite math useful？', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/020.jpg', '3blue1brown/020.mp4', 1097, 0, 'oss', NULL),
  (152, 'How AI connects text and images', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/021.jpg', '3blue1brown/021.mp4', 102, 0, 'oss', NULL),
  (153, 'How I animate 3Blue1Brown ｜ A Manim demo with Ben Sparks', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/022.jpg', '3blue1brown/022.mp4', 3220, 0, 'oss', NULL),
  (154, 'How might LLMs store facts ｜ Deep Learning Chapter 7', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/023.jpg', '3blue1brown/023.mp4', 1362, 0, 'oss', NULL),
  (155, 'How word vectors encode meaning', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/024.jpg', '3blue1brown/024.mp4', 59, 0, 'oss', NULL),
  (156, 'LLMs are next-word predictors', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/025.jpg', '3blue1brown/025.mp4', 48, 0, 'oss', NULL),
  (157, 'Linear transformations and matrices ｜ Chapter 3, Essence of linear algebra', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/026.jpg', '3blue1brown/026.mp4', 658, 0, 'oss', NULL),
  (158, 'Reinventing Entropy ｜ Compression is Intelligence Part 1', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/027.jpg', '3blue1brown/027.mp4', 1939, 0, 'oss', NULL),
  (159, 'Simulating the electric field and a moving charge', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/028.jpg', '3blue1brown/028.mp4', 59, 0, 'oss', NULL),
  (160, 'Taylor series ｜ Chapter 11, Essence of calculus', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/029.jpg', '3blue1brown/029.mp4', 1339, 0, 'oss', NULL),
  (161, 'Temperature in LLMs', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/030.jpg', '3blue1brown/030.mp4', 59, 0, 'oss', NULL),
  (162, 'The Newton art puzzle', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/031.jpg', '3blue1brown/031.mp4', 59, 0, 'oss', NULL),
  (163, 'The Physics of Euler''s Formula ｜ Laplace Transform Prelude', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/032.jpg', '3blue1brown/032.mp4', 1668, 0, 'oss', NULL),
  (164, 'The last IMO problem AI could not solve', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/033.jpg', '3blue1brown/033.mp4', 3115, 0, 'oss', NULL),
  (165, 'The most beautiful formula not enough people understand', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/034.jpg', '3blue1brown/034.mp4', 3623, 0, 'oss', NULL),
  (166, 'The scale of training LLMs', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/035.jpg', '3blue1brown/035.mp4', 31, 0, 'oss', NULL),
  (167, 'The subset sum puzzle', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/036.jpg', '3blue1brown/036.mp4', 48, 0, 'oss', NULL),
  (168, 'Transformers, the tech behind LLMs ｜ Deep Learning Chapter 5', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/037.jpg', '3blue1brown/037.mp4', 1633, 0, 'oss', NULL),
  (169, 'Vectors ｜ Chapter 1, Essence of linear algebra', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/038.jpg', '3blue1brown/038.mp4', 591, 0, 'oss', NULL),
  (170, 'Why Laplace transforms are so useful', 9, 11, 'https://zhishu-video-ai.oss-cn-beijing.aliyuncs.com/covers/3blue1brown/039.jpg', '3blue1brown/039.mp4', 1384, 0, 'oss', NULL);

INSERT INTO tag (id, name) VALUES
  (1, 'RAG'),
  (2, '向量数据库'),
  (3, 'Embedding'),
  (4, 'Agent'),
  (5, '工具调用'),
  (6, 'MCP'),
  (7, '提示词'),
  (8, '原理'),
  (9, '深度学习'),
  (10, 'Transformer'),
  (11, '线性代数'),
  (12, '微积分'),
  (13, '概率统计'),
  (14, '信号处理');

INSERT INTO article (id, title, blogger_id, cover, content_url, source_url, source_title, author_name, summary, content_md, category_key, hot_score, published_at, status) VALUES
  (1, '2026年做RAG，这些坑别再踩了', 1, 'https://placehold.co/400x225?text=Article', 'https://example.com/articles/rag-pits', 'https://example.com/articles/rag-pits', NULL, NULL, '检索质量、切块策略与评估缺失，是 RAG 落地最常见的三大坑。', '## 三大坑
- **检索质量**：向量召回不相关片段，污染上下文
- **切块策略**：过粗或过细都会拉低召回
- **评估缺失**：没有 ground truth 就无法量化效果

**建议**：先搭建评估集，再迭代检索与切块策略。', 'rag', 880, '2026-09-28 10:00:00', 'published'),
  (2, 'MCP能让Claude接入你的数据库吗', 3, 'https://placehold.co/400x225?text=Article', 'https://example.com/articles/mcp-db', 'https://example.com/articles/mcp-db', NULL, NULL, 'MCP 把工具调用标准化，让 Claude 能经 MCP server 直连数据库。', '## 核心思路
MCP（Model Context Protocol）把工具调用标准化，Claude 可经 MCP server 直连数据库。

**要点**
- 只读优先，写操作加白名单
- 连接信息走环境变量，不入库
- 返回结果截断，防止超上下文', 'mcp', 720, '2026-09-29 10:00:00', 'published'),
  (3, 'Agent框架选型指南', 2, 'https://placehold.co/400x225?text=Article', 'https://example.com/articles/agent-select', 'https://example.com/articles/agent-select', NULL, NULL, '主流 Agent 框架的能力边界与选型要点对比。', '## 选型维度
- **编排能力**：多 Agent 协作与工具编排
- **生态**：插件与社区成熟度
- **可控性**：状态可观测、可回滚

**结论**：先按场景反推框架，避免过度设计。', 'harness', 690, '2026-09-30 10:00:00', 'published'),
  (4, 'MCP协议深度解析：从入门到实战', 5, 'https://placehold.co/400x225?text=MCP+Deep', 'https://example.com/articles/mcp-deep-dive', 'https://example.com/articles/mcp-deep-dive', NULL, NULL, '从协议构成到代码级实战，讲清 MCP 的完整链路。', '## 协议构成
MCP 由 host、client、server 三部分组成，走 JSON-RPC 通信。

**实战要点**
- 定义 tools 与 resources
- 处理 initialize 握手
- 权限与超时治理', 'mcp', 850, '2026-10-01 09:00:00', 'published'),
  (5, 'Agent开发实战：用Claude Code打造你的第一个智能体', 5, 'https://placehold.co/400x225?text=Agent+Dev', 'https://example.com/articles/agent-dev', 'https://example.com/articles/agent-dev', NULL, NULL, '用 Claude Code 从零构建一个可用的智能体，含关键取舍。', '## 实战路径
- **明确边界**：把任务拆成可验证的子步骤
- **工具设计**：工具即能力，围绕目标定义
- **上下文管理**：精简注入，避免噪声

**收尾**：健壮的错误处理与日志，是可维护的关键。', 'harness', 920, '2026-10-01 10:00:00', 'published'),
  (6, 'RAG系统优化指南：从检索到生成的完整链路', 5, 'https://placehold.co/400x225?text=RAG+Guide', 'https://example.com/articles/rag-guide', 'https://example.com/articles/rag-guide', NULL, NULL, '覆盖检索、重排、生成三段的 RAG 系统化优化清单。', '## 三段优化
- **检索**：混合召回 + 元数据过滤
- **重排**：rerank 模型提升相关度
- **生成**：约束引用、抑制幻觉

**落地顺序**：先评估、再优化检索、最后调生成。', 'rag', 780, '2026-10-02 09:00:00', 'published');

INSERT INTO video_tag (video_id, tag_id) VALUES
  (10, 4), (10, 5), (11, 4), (11, 5),
  (12, 4), (12, 5), (13, 4), (13, 5),
  (14, 4), (14, 5), (14, 6),
  (15, 4), (15, 5),
  (16, 4),
  (20, 6), (21, 6), (22, 6), (23, 6), (30, 6),
  (24, 4),
  (26, 1), (26, 2), (26, 3),
  (27, 7),
  (31, 4),
  (32, 4), (32, 5),
  (33, 1), (33, 2), (33, 3),
  (34, 1), (34, 2), (34, 3),
  (37, 4),
  (37, 5),
  (41, 4),
  (41, 5),
  (44, 4),
  (44, 5),
  (44, 6),
  (46, 4),
  (46, 5),
  (47, 4),
  (47, 5),
  (48, 4),
  (48, 5),
  (51, 4),
  (51, 5),
  (52, 4),
  (52, 5),
  (52, 6),
  (53, 4),
  (53, 5),
  (53, 6),
  (54, 4),
  (54, 5),
  (54, 6),
  (55, 4),
  (55, 5),
  (55, 6),
  (56, 1),
  (56, 2),
  (56, 3),
  (58, 4),
  (58, 5),
  (59, 4),
  (59, 5),
  (59, 6),
  (60, 4),
  (60, 5),
  (60, 6),
  (61, 4),
  (61, 5),
  (62, 4),
  (62, 5),
  (63, 4),
  (63, 5),
  (63, 6),
  (64, 4),
  (64, 5),
  (64, 6),
  (65, 4),
  (65, 5),
  (65, 6),
  (66, 7),
  (67, 4),
  (67, 5),
  (68, 4),
  (68, 5),
  (69, 4),
  (69, 5),
  (74, 4),
  (74, 5),
  (74, 6),
  (75, 4),
  (75, 5),
  (75, 6),
  (76, 4),
  (76, 5),
  (76, 6),
  (79, 4),
  (79, 5),
  (79, 6),
  (80, 4),
  (80, 5),
  (80, 6),
  (81, 4),
  (81, 5),
  (81, 6),
  (83, 4),
  (83, 5),
  (83, 6),
  (85, 4),
  (85, 5),
  (85, 6),
  (90, 7),
  (93, 4),
  (93, 5),
  (93, 6),
  (94, 4),
  (94, 5),
  (94, 6),
  (95, 4),
  (95, 5),
  (95, 6),
  (96, 4),
  (96, 5),
  (96, 6);

INSERT INTO video_tag (video_id, tag_id) VALUES
  (97, 4),
  (97, 5),
  (98, 4),
  (98, 5),
  (99, 4),
  (99, 5),
  (100, 4),
  (101, 4),
  (102, 4),
  (103, 4),
  (103, 5),
  (104, 4),
  (104, 5),
  (105, 1),
  (105, 4),
  (105, 5),
  (106, 4),
  (106, 5),
  (107, 4),
  (107, 5),
  (108, 4),
  (109, 4),
  (110, 4),
  (111, 4),
  (112, 4),
  (113, 4),
  (113, 5),
  (114, 4),
  (114, 5),
  (115, 8),
  (115, 9),
  (116, 4),
  (117, 4),
  (118, 4),
  (118, 5),
  (119, 4),
  (120, 8),
  (120, 9),
  (121, 8),
  (121, 9),
  (122, 8),
  (122, 9),
  (122, 10),
  (123, 8),
  (123, 9),
  (124, 4),
  (124, 5),
  (125, 8),
  (125, 9),
  (126, 4),
  (127, 4),
  (127, 8),
  (128, 8),
  (128, 9),
  (129, 4),
  (129, 8),
  (129, 9),
  (130, 4),
  (131, 8),
  (131, 9),
  (132, 8),
  (132, 13),
  (133, 8),
  (133, 9),
  (133, 14),
  (134, 8),
  (134, 9),
  (134, 10),
  (135, 8),
  (135, 9),
  (135, 12),
  (136, 8),
  (136, 9),
  (136, 12),
  (137, 8),
  (137, 13),
  (138, 8),
  (138, 9),
  (139, 8),
  (139, 12),
  (139, 14),
  (140, 8),
  (140, 12),
  (140, 14),
  (141, 8),
  (141, 14),
  (142, 8),
  (142, 9),
  (143, 8),
  (143, 9),
  (143, 13),
  (144, 8),
  (145, 8),
  (145, 14),
  (146, 8),
  (146, 11),
  (147, 8),
  (147, 13),
  (147, 14),
  (148, 8),
  (148, 12),
  (149, 8),
  (149, 11),
  (150, 8),
  (150, 9),
  (150, 12),
  (151, 8),
  (152, 8),
  (152, 9),
  (153, 8),
  (154, 8),
  (154, 9),
  (154, 10),
  (155, 8),
  (155, 9),
  (156, 8),
  (156, 9),
  (156, 10),
  (157, 8),
  (157, 11),
  (158, 8),
  (158, 13),
  (159, 8),
  (159, 12),
  (160, 8),
  (160, 12),
  (161, 8),
  (161, 9),
  (162, 8),
  (163, 8),
  (163, 12),
  (164, 8),
  (165, 8),
  (166, 8),
  (166, 9),
  (167, 8),
  (168, 8),
  (168, 9),
  (168, 10),
  (169, 8),
  (169, 11),
  (170, 8),
  (170, 14);
